// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gw.proto

package gw // import "github.com/brocaar/loraserver/api/gw"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/brocaar/loraserver/api/common"
import duration "github.com/golang/protobuf/ptypes/duration"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FineTimestampType int32

const (
	// No fine-timestamp available.
	FineTimestampType_NONE FineTimestampType = 0
	// Encrypted fine-timestamp.
	FineTimestampType_ENCRYPTED FineTimestampType = 1
	// Plain fine-timestamp.
	FineTimestampType_PLAIN FineTimestampType = 2
)

var FineTimestampType_name = map[int32]string{
	0: "NONE",
	1: "ENCRYPTED",
	2: "PLAIN",
}
var FineTimestampType_value = map[string]int32{
	"NONE":      0,
	"ENCRYPTED": 1,
	"PLAIN":     2,
}

func (x FineTimestampType) String() string {
	return proto.EnumName(FineTimestampType_name, int32(x))
}
func (FineTimestampType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_gw_c5d2c5c9c486fb40, []int{0}
}

type UplinkTXInfo struct {
	// Frequency (Hz).
	Frequency uint32 `protobuf:"varint,1,opt,name=frequency,proto3" json:"frequency,omitempty"`
	// Modulation.
	Modulation common.Modulation `protobuf:"varint,2,opt,name=modulation,proto3,enum=common.Modulation" json:"modulation,omitempty"`
	// Types that are valid to be assigned to ModulationInfo:
	//	*UplinkTXInfo_LoraModulationInfo
	//	*UplinkTXInfo_FskModulationInfo
	ModulationInfo       isUplinkTXInfo_ModulationInfo `protobuf_oneof:"modulation_info"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *UplinkTXInfo) Reset()         { *m = UplinkTXInfo{} }
func (m *UplinkTXInfo) String() string { return proto.CompactTextString(m) }
func (*UplinkTXInfo) ProtoMessage()    {}
func (*UplinkTXInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_gw_c5d2c5c9c486fb40, []int{0}
}
func (m *UplinkTXInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UplinkTXInfo.Unmarshal(m, b)
}
func (m *UplinkTXInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UplinkTXInfo.Marshal(b, m, deterministic)
}
func (dst *UplinkTXInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UplinkTXInfo.Merge(dst, src)
}
func (m *UplinkTXInfo) XXX_Size() int {
	return xxx_messageInfo_UplinkTXInfo.Size(m)
}
func (m *UplinkTXInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UplinkTXInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UplinkTXInfo proto.InternalMessageInfo

type isUplinkTXInfo_ModulationInfo interface {
	isUplinkTXInfo_ModulationInfo()
}

type UplinkTXInfo_LoraModulationInfo struct {
	LoraModulationInfo *LoRaModulationInfo `protobuf:"bytes,3,opt,name=lora_modulation_info,json=loraModulationInfo,proto3,oneof"`
}
type UplinkTXInfo_FskModulationInfo struct {
	FskModulationInfo *FSKModulationInfo `protobuf:"bytes,4,opt,name=fsk_modulation_info,json=fskModulationInfo,proto3,oneof"`
}

func (*UplinkTXInfo_LoraModulationInfo) isUplinkTXInfo_ModulationInfo() {}
func (*UplinkTXInfo_FskModulationInfo) isUplinkTXInfo_ModulationInfo()  {}

func (m *UplinkTXInfo) GetModulationInfo() isUplinkTXInfo_ModulationInfo {
	if m != nil {
		return m.ModulationInfo
	}
	return nil
}

func (m *UplinkTXInfo) GetFrequency() uint32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *UplinkTXInfo) GetModulation() common.Modulation {
	if m != nil {
		return m.Modulation
	}
	return common.Modulation_LORA
}

func (m *UplinkTXInfo) GetLoraModulationInfo() *LoRaModulationInfo {
	if x, ok := m.GetModulationInfo().(*UplinkTXInfo_LoraModulationInfo); ok {
		return x.LoraModulationInfo
	}
	return nil
}

func (m *UplinkTXInfo) GetFskModulationInfo() *FSKModulationInfo {
	if x, ok := m.GetModulationInfo().(*UplinkTXInfo_FskModulationInfo); ok {
		return x.FskModulationInfo
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UplinkTXInfo) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UplinkTXInfo_OneofMarshaler, _UplinkTXInfo_OneofUnmarshaler, _UplinkTXInfo_OneofSizer, []interface{}{
		(*UplinkTXInfo_LoraModulationInfo)(nil),
		(*UplinkTXInfo_FskModulationInfo)(nil),
	}
}

func _UplinkTXInfo_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UplinkTXInfo)
	// modulation_info
	switch x := m.ModulationInfo.(type) {
	case *UplinkTXInfo_LoraModulationInfo:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LoraModulationInfo); err != nil {
			return err
		}
	case *UplinkTXInfo_FskModulationInfo:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FskModulationInfo); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("UplinkTXInfo.ModulationInfo has unexpected type %T", x)
	}
	return nil
}

func _UplinkTXInfo_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UplinkTXInfo)
	switch tag {
	case 3: // modulation_info.lora_modulation_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoRaModulationInfo)
		err := b.DecodeMessage(msg)
		m.ModulationInfo = &UplinkTXInfo_LoraModulationInfo{msg}
		return true, err
	case 4: // modulation_info.fsk_modulation_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FSKModulationInfo)
		err := b.DecodeMessage(msg)
		m.ModulationInfo = &UplinkTXInfo_FskModulationInfo{msg}
		return true, err
	default:
		return false, nil
	}
}

func _UplinkTXInfo_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UplinkTXInfo)
	// modulation_info
	switch x := m.ModulationInfo.(type) {
	case *UplinkTXInfo_LoraModulationInfo:
		s := proto.Size(x.LoraModulationInfo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UplinkTXInfo_FskModulationInfo:
		s := proto.Size(x.FskModulationInfo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type LoRaModulationInfo struct {
	// Bandwidth.
	Bandwidth uint32 `protobuf:"varint,1,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	// Speading-factor.
	SpreadingFactor uint32 `protobuf:"varint,2,opt,name=spreading_factor,json=spreadingFactor,proto3" json:"spreading_factor,omitempty"`
	// Code-rate.
	CodeRate string `protobuf:"bytes,3,opt,name=code_rate,json=codeRate,proto3" json:"code_rate,omitempty"`
	// Polarization inversion.
	PolarizationInversion bool     `protobuf:"varint,4,opt,name=polarization_inversion,json=polarizationInversion,proto3" json:"polarization_inversion,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *LoRaModulationInfo) Reset()         { *m = LoRaModulationInfo{} }
func (m *LoRaModulationInfo) String() string { return proto.CompactTextString(m) }
func (*LoRaModulationInfo) ProtoMessage()    {}
func (*LoRaModulationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_gw_c5d2c5c9c486fb40, []int{1}
}
func (m *LoRaModulationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoRaModulationInfo.Unmarshal(m, b)
}
func (m *LoRaModulationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoRaModulationInfo.Marshal(b, m, deterministic)
}
func (dst *LoRaModulationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoRaModulationInfo.Merge(dst, src)
}
func (m *LoRaModulationInfo) XXX_Size() int {
	return xxx_messageInfo_LoRaModulationInfo.Size(m)
}
func (m *LoRaModulationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoRaModulationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoRaModulationInfo proto.InternalMessageInfo

func (m *LoRaModulationInfo) GetBandwidth() uint32 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

func (m *LoRaModulationInfo) GetSpreadingFactor() uint32 {
	if m != nil {
		return m.SpreadingFactor
	}
	return 0
}

func (m *LoRaModulationInfo) GetCodeRate() string {
	if m != nil {
		return m.CodeRate
	}
	return ""
}

func (m *LoRaModulationInfo) GetPolarizationInversion() bool {
	if m != nil {
		return m.PolarizationInversion
	}
	return false
}

type FSKModulationInfo struct {
	// Bandwidth.
	Bandwidth uint32 `protobuf:"varint,1,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	// Bitrate.
	Bitrate              uint32   `protobuf:"varint,2,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FSKModulationInfo) Reset()         { *m = FSKModulationInfo{} }
func (m *FSKModulationInfo) String() string { return proto.CompactTextString(m) }
func (*FSKModulationInfo) ProtoMessage()    {}
func (*FSKModulationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_gw_c5d2c5c9c486fb40, []int{2}
}
func (m *FSKModulationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FSKModulationInfo.Unmarshal(m, b)
}
func (m *FSKModulationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FSKModulationInfo.Marshal(b, m, deterministic)
}
func (dst *FSKModulationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FSKModulationInfo.Merge(dst, src)
}
func (m *FSKModulationInfo) XXX_Size() int {
	return xxx_messageInfo_FSKModulationInfo.Size(m)
}
func (m *FSKModulationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FSKModulationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FSKModulationInfo proto.InternalMessageInfo

func (m *FSKModulationInfo) GetBandwidth() uint32 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

func (m *FSKModulationInfo) GetBitrate() uint32 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

type EncryptedFineTimestamp struct {
	// AES key index used for encrypting the fine timestamp.
	AesKeyIndex uint32 `protobuf:"varint,1,opt,name=aes_key_index,json=aesKeyIndex,proto3" json:"aes_key_index,omitempty"`
	// Encrypted 'main' fine-timestamp (ns precision part of the timestamp).
	EncryptedNs          []byte   `protobuf:"bytes,2,opt,name=encrypted_ns,json=encryptedNs,proto3" json:"encrypted_ns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedFineTimestamp) Reset()         { *m = EncryptedFineTimestamp{} }
func (m *EncryptedFineTimestamp) String() string { return proto.CompactTextString(m) }
func (*EncryptedFineTimestamp) ProtoMessage()    {}
func (*EncryptedFineTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_gw_c5d2c5c9c486fb40, []int{3}
}
func (m *EncryptedFineTimestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedFineTimestamp.Unmarshal(m, b)
}
func (m *EncryptedFineTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedFineTimestamp.Marshal(b, m, deterministic)
}
func (dst *EncryptedFineTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedFineTimestamp.Merge(dst, src)
}
func (m *EncryptedFineTimestamp) XXX_Size() int {
	return xxx_messageInfo_EncryptedFineTimestamp.Size(m)
}
func (m *EncryptedFineTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedFineTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedFineTimestamp proto.InternalMessageInfo

func (m *EncryptedFineTimestamp) GetAesKeyIndex() uint32 {
	if m != nil {
		return m.AesKeyIndex
	}
	return 0
}

func (m *EncryptedFineTimestamp) GetEncryptedNs() []byte {
	if m != nil {
		return m.EncryptedNs
	}
	return nil
}

type PlainFineTimestamp struct {
	// Full timestamp.
	Time                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PlainFineTimestamp) Reset()         { *m = PlainFineTimestamp{} }
func (m *PlainFineTimestamp) String() string { return proto.CompactTextString(m) }
func (*PlainFineTimestamp) ProtoMessage()    {}
func (*PlainFineTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_gw_c5d2c5c9c486fb40, []int{4}
}
func (m *PlainFineTimestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlainFineTimestamp.Unmarshal(m, b)
}
func (m *PlainFineTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlainFineTimestamp.Marshal(b, m, deterministic)
}
func (dst *PlainFineTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlainFineTimestamp.Merge(dst, src)
}
func (m *PlainFineTimestamp) XXX_Size() int {
	return xxx_messageInfo_PlainFineTimestamp.Size(m)
}
func (m *PlainFineTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_PlainFineTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_PlainFineTimestamp proto.InternalMessageInfo

func (m *PlainFineTimestamp) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type UplinkRXInfo struct {
	// Gateway ID.
	GatewayId []byte `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	// RX time (only set when the gateway has a GPS module).
	Time *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	// RX time since GPS epoch (only set when the gateway has a GPS module).
	TimeSinceGpsEpoch *duration.Duration `protobuf:"bytes,3,opt,name=time_since_gps_epoch,json=timeSinceGpsEpoch,proto3" json:"time_since_gps_epoch,omitempty"`
	// Gateway internal timestamp.
	Timestamp uint32 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// RSSI.
	Rssi int32 `protobuf:"varint,5,opt,name=rssi,proto3" json:"rssi,omitempty"`
	// LoRa SNR.
	LoraSnr float64 `protobuf:"fixed64,6,opt,name=lora_snr,json=loraSnr,proto3" json:"lora_snr,omitempty"`
	// Channel.
	Channel uint32 `protobuf:"varint,7,opt,name=channel,proto3" json:"channel,omitempty"`
	// RF Chain.
	RfChain uint32 `protobuf:"varint,8,opt,name=rf_chain,json=rfChain,proto3" json:"rf_chain,omitempty"`
	// Board.
	Board uint32 `protobuf:"varint,9,opt,name=board,proto3" json:"board,omitempty"`
	// Antenna.
	Antenna uint32 `protobuf:"varint,10,opt,name=antenna,proto3" json:"antenna,omitempty"`
	// Location.
	Location *common.Location `protobuf:"bytes,11,opt,name=location,proto3" json:"location,omitempty"`
	// Fine-timestamp type.
	FineTimestampType FineTimestampType `protobuf:"varint,12,opt,name=fine_timestamp_type,json=fineTimestampType,proto3,enum=gw.FineTimestampType" json:"fine_timestamp_type,omitempty"`
	// Fine-timestamp data.
	//
	// Types that are valid to be assigned to FineTimestamp:
	//	*UplinkRXInfo_EncryptedFineTimestamp
	//	*UplinkRXInfo_PlainFineTimestamp
	FineTimestamp        isUplinkRXInfo_FineTimestamp `protobuf_oneof:"fine_timestamp"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *UplinkRXInfo) Reset()         { *m = UplinkRXInfo{} }
func (m *UplinkRXInfo) String() string { return proto.CompactTextString(m) }
func (*UplinkRXInfo) ProtoMessage()    {}
func (*UplinkRXInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_gw_c5d2c5c9c486fb40, []int{5}
}
func (m *UplinkRXInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UplinkRXInfo.Unmarshal(m, b)
}
func (m *UplinkRXInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UplinkRXInfo.Marshal(b, m, deterministic)
}
func (dst *UplinkRXInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UplinkRXInfo.Merge(dst, src)
}
func (m *UplinkRXInfo) XXX_Size() int {
	return xxx_messageInfo_UplinkRXInfo.Size(m)
}
func (m *UplinkRXInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UplinkRXInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UplinkRXInfo proto.InternalMessageInfo

type isUplinkRXInfo_FineTimestamp interface {
	isUplinkRXInfo_FineTimestamp()
}

type UplinkRXInfo_EncryptedFineTimestamp struct {
	EncryptedFineTimestamp *EncryptedFineTimestamp `protobuf:"bytes,13,opt,name=encrypted_fine_timestamp,json=encryptedFineTimestamp,proto3,oneof"`
}
type UplinkRXInfo_PlainFineTimestamp struct {
	PlainFineTimestamp *PlainFineTimestamp `protobuf:"bytes,14,opt,name=plain_fine_timestamp,json=plainFineTimestamp,proto3,oneof"`
}

func (*UplinkRXInfo_EncryptedFineTimestamp) isUplinkRXInfo_FineTimestamp() {}
func (*UplinkRXInfo_PlainFineTimestamp) isUplinkRXInfo_FineTimestamp()     {}

func (m *UplinkRXInfo) GetFineTimestamp() isUplinkRXInfo_FineTimestamp {
	if m != nil {
		return m.FineTimestamp
	}
	return nil
}

func (m *UplinkRXInfo) GetGatewayId() []byte {
	if m != nil {
		return m.GatewayId
	}
	return nil
}

func (m *UplinkRXInfo) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *UplinkRXInfo) GetTimeSinceGpsEpoch() *duration.Duration {
	if m != nil {
		return m.TimeSinceGpsEpoch
	}
	return nil
}

func (m *UplinkRXInfo) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *UplinkRXInfo) GetRssi() int32 {
	if m != nil {
		return m.Rssi
	}
	return 0
}

func (m *UplinkRXInfo) GetLoraSnr() float64 {
	if m != nil {
		return m.LoraSnr
	}
	return 0
}

func (m *UplinkRXInfo) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *UplinkRXInfo) GetRfChain() uint32 {
	if m != nil {
		return m.RfChain
	}
	return 0
}

func (m *UplinkRXInfo) GetBoard() uint32 {
	if m != nil {
		return m.Board
	}
	return 0
}

func (m *UplinkRXInfo) GetAntenna() uint32 {
	if m != nil {
		return m.Antenna
	}
	return 0
}

func (m *UplinkRXInfo) GetLocation() *common.Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *UplinkRXInfo) GetFineTimestampType() FineTimestampType {
	if m != nil {
		return m.FineTimestampType
	}
	return FineTimestampType_NONE
}

func (m *UplinkRXInfo) GetEncryptedFineTimestamp() *EncryptedFineTimestamp {
	if x, ok := m.GetFineTimestamp().(*UplinkRXInfo_EncryptedFineTimestamp); ok {
		return x.EncryptedFineTimestamp
	}
	return nil
}

func (m *UplinkRXInfo) GetPlainFineTimestamp() *PlainFineTimestamp {
	if x, ok := m.GetFineTimestamp().(*UplinkRXInfo_PlainFineTimestamp); ok {
		return x.PlainFineTimestamp
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UplinkRXInfo) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UplinkRXInfo_OneofMarshaler, _UplinkRXInfo_OneofUnmarshaler, _UplinkRXInfo_OneofSizer, []interface{}{
		(*UplinkRXInfo_EncryptedFineTimestamp)(nil),
		(*UplinkRXInfo_PlainFineTimestamp)(nil),
	}
}

func _UplinkRXInfo_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UplinkRXInfo)
	// fine_timestamp
	switch x := m.FineTimestamp.(type) {
	case *UplinkRXInfo_EncryptedFineTimestamp:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EncryptedFineTimestamp); err != nil {
			return err
		}
	case *UplinkRXInfo_PlainFineTimestamp:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PlainFineTimestamp); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("UplinkRXInfo.FineTimestamp has unexpected type %T", x)
	}
	return nil
}

func _UplinkRXInfo_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UplinkRXInfo)
	switch tag {
	case 13: // fine_timestamp.encrypted_fine_timestamp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EncryptedFineTimestamp)
		err := b.DecodeMessage(msg)
		m.FineTimestamp = &UplinkRXInfo_EncryptedFineTimestamp{msg}
		return true, err
	case 14: // fine_timestamp.plain_fine_timestamp
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PlainFineTimestamp)
		err := b.DecodeMessage(msg)
		m.FineTimestamp = &UplinkRXInfo_PlainFineTimestamp{msg}
		return true, err
	default:
		return false, nil
	}
}

func _UplinkRXInfo_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UplinkRXInfo)
	// fine_timestamp
	switch x := m.FineTimestamp.(type) {
	case *UplinkRXInfo_EncryptedFineTimestamp:
		s := proto.Size(x.EncryptedFineTimestamp)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UplinkRXInfo_PlainFineTimestamp:
		s := proto.Size(x.PlainFineTimestamp)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type DownlinkTXInfo struct {
	// Gateway ID.
	GatewayId []byte `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	// Frame must be sent immediately.
	Immediately bool `protobuf:"varint,2,opt,name=immediately,proto3" json:"immediately,omitempty"`
	// Emit frame at the given time since GPS epoch.
	TimeSinceGpsEpoch *duration.Duration `protobuf:"bytes,3,opt,name=time_since_gps_epoch,json=timeSinceGpsEpoch,proto3" json:"time_since_gps_epoch,omitempty"`
	// Emit the frame at the given gateway internal timestamp.
	Timestamp uint32 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// TX frequency (in Hz).
	Frequency uint32 `protobuf:"varint,5,opt,name=frequency,proto3" json:"frequency,omitempty"`
	// TX power (in dBm).
	Power int32 `protobuf:"varint,6,opt,name=power,proto3" json:"power,omitempty"`
	// Modulation.
	Modulation common.Modulation `protobuf:"varint,7,opt,name=modulation,proto3,enum=common.Modulation" json:"modulation,omitempty"`
	// Types that are valid to be assigned to ModulationInfo:
	//	*DownlinkTXInfo_LoraModulationInfo
	//	*DownlinkTXInfo_FskModulationInfo
	ModulationInfo isDownlinkTXInfo_ModulationInfo `protobuf_oneof:"modulation_info"`
	// The board identifier for emitting the frame.
	Board uint32 `protobuf:"varint,10,opt,name=board,proto3" json:"board,omitempty"`
	// The antenna identifier for emitting the frame.
	Antenna              uint32   `protobuf:"varint,11,opt,name=antenna,proto3" json:"antenna,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownlinkTXInfo) Reset()         { *m = DownlinkTXInfo{} }
func (m *DownlinkTXInfo) String() string { return proto.CompactTextString(m) }
func (*DownlinkTXInfo) ProtoMessage()    {}
func (*DownlinkTXInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_gw_c5d2c5c9c486fb40, []int{6}
}
func (m *DownlinkTXInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownlinkTXInfo.Unmarshal(m, b)
}
func (m *DownlinkTXInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownlinkTXInfo.Marshal(b, m, deterministic)
}
func (dst *DownlinkTXInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownlinkTXInfo.Merge(dst, src)
}
func (m *DownlinkTXInfo) XXX_Size() int {
	return xxx_messageInfo_DownlinkTXInfo.Size(m)
}
func (m *DownlinkTXInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DownlinkTXInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DownlinkTXInfo proto.InternalMessageInfo

type isDownlinkTXInfo_ModulationInfo interface {
	isDownlinkTXInfo_ModulationInfo()
}

type DownlinkTXInfo_LoraModulationInfo struct {
	LoraModulationInfo *LoRaModulationInfo `protobuf:"bytes,8,opt,name=lora_modulation_info,json=loraModulationInfo,proto3,oneof"`
}
type DownlinkTXInfo_FskModulationInfo struct {
	FskModulationInfo *FSKModulationInfo `protobuf:"bytes,9,opt,name=fsk_modulation_info,json=fskModulationInfo,proto3,oneof"`
}

func (*DownlinkTXInfo_LoraModulationInfo) isDownlinkTXInfo_ModulationInfo() {}
func (*DownlinkTXInfo_FskModulationInfo) isDownlinkTXInfo_ModulationInfo()  {}

func (m *DownlinkTXInfo) GetModulationInfo() isDownlinkTXInfo_ModulationInfo {
	if m != nil {
		return m.ModulationInfo
	}
	return nil
}

func (m *DownlinkTXInfo) GetGatewayId() []byte {
	if m != nil {
		return m.GatewayId
	}
	return nil
}

func (m *DownlinkTXInfo) GetImmediately() bool {
	if m != nil {
		return m.Immediately
	}
	return false
}

func (m *DownlinkTXInfo) GetTimeSinceGpsEpoch() *duration.Duration {
	if m != nil {
		return m.TimeSinceGpsEpoch
	}
	return nil
}

func (m *DownlinkTXInfo) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *DownlinkTXInfo) GetFrequency() uint32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *DownlinkTXInfo) GetPower() int32 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *DownlinkTXInfo) GetModulation() common.Modulation {
	if m != nil {
		return m.Modulation
	}
	return common.Modulation_LORA
}

func (m *DownlinkTXInfo) GetLoraModulationInfo() *LoRaModulationInfo {
	if x, ok := m.GetModulationInfo().(*DownlinkTXInfo_LoraModulationInfo); ok {
		return x.LoraModulationInfo
	}
	return nil
}

func (m *DownlinkTXInfo) GetFskModulationInfo() *FSKModulationInfo {
	if x, ok := m.GetModulationInfo().(*DownlinkTXInfo_FskModulationInfo); ok {
		return x.FskModulationInfo
	}
	return nil
}

func (m *DownlinkTXInfo) GetBoard() uint32 {
	if m != nil {
		return m.Board
	}
	return 0
}

func (m *DownlinkTXInfo) GetAntenna() uint32 {
	if m != nil {
		return m.Antenna
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*DownlinkTXInfo) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _DownlinkTXInfo_OneofMarshaler, _DownlinkTXInfo_OneofUnmarshaler, _DownlinkTXInfo_OneofSizer, []interface{}{
		(*DownlinkTXInfo_LoraModulationInfo)(nil),
		(*DownlinkTXInfo_FskModulationInfo)(nil),
	}
}

func _DownlinkTXInfo_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*DownlinkTXInfo)
	// modulation_info
	switch x := m.ModulationInfo.(type) {
	case *DownlinkTXInfo_LoraModulationInfo:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LoraModulationInfo); err != nil {
			return err
		}
	case *DownlinkTXInfo_FskModulationInfo:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FskModulationInfo); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("DownlinkTXInfo.ModulationInfo has unexpected type %T", x)
	}
	return nil
}

func _DownlinkTXInfo_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*DownlinkTXInfo)
	switch tag {
	case 8: // modulation_info.lora_modulation_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoRaModulationInfo)
		err := b.DecodeMessage(msg)
		m.ModulationInfo = &DownlinkTXInfo_LoraModulationInfo{msg}
		return true, err
	case 9: // modulation_info.fsk_modulation_info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FSKModulationInfo)
		err := b.DecodeMessage(msg)
		m.ModulationInfo = &DownlinkTXInfo_FskModulationInfo{msg}
		return true, err
	default:
		return false, nil
	}
}

func _DownlinkTXInfo_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*DownlinkTXInfo)
	// modulation_info
	switch x := m.ModulationInfo.(type) {
	case *DownlinkTXInfo_LoraModulationInfo:
		s := proto.Size(x.LoraModulationInfo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DownlinkTXInfo_FskModulationInfo:
		s := proto.Size(x.FskModulationInfo)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type UplinkFrame struct {
	// PHYPayload.
	PhyPayload []byte `protobuf:"bytes,1,opt,name=phy_payload,json=phyPayload,proto3" json:"phy_payload,omitempty"`
	// TX meta-data.
	TxInfo *UplinkTXInfo `protobuf:"bytes,2,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// RX meta-data.
	RxInfo               *UplinkRXInfo `protobuf:"bytes,3,opt,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UplinkFrame) Reset()         { *m = UplinkFrame{} }
func (m *UplinkFrame) String() string { return proto.CompactTextString(m) }
func (*UplinkFrame) ProtoMessage()    {}
func (*UplinkFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_gw_c5d2c5c9c486fb40, []int{7}
}
func (m *UplinkFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UplinkFrame.Unmarshal(m, b)
}
func (m *UplinkFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UplinkFrame.Marshal(b, m, deterministic)
}
func (dst *UplinkFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UplinkFrame.Merge(dst, src)
}
func (m *UplinkFrame) XXX_Size() int {
	return xxx_messageInfo_UplinkFrame.Size(m)
}
func (m *UplinkFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_UplinkFrame.DiscardUnknown(m)
}

var xxx_messageInfo_UplinkFrame proto.InternalMessageInfo

func (m *UplinkFrame) GetPhyPayload() []byte {
	if m != nil {
		return m.PhyPayload
	}
	return nil
}

func (m *UplinkFrame) GetTxInfo() *UplinkTXInfo {
	if m != nil {
		return m.TxInfo
	}
	return nil
}

func (m *UplinkFrame) GetRxInfo() *UplinkRXInfo {
	if m != nil {
		return m.RxInfo
	}
	return nil
}

type UplinkFrameSet struct {
	// PHYPayload.
	PhyPayload []byte `protobuf:"bytes,1,opt,name=phy_payload,json=phyPayload,proto3" json:"phy_payload,omitempty"`
	// TX meta-data.
	TxInfo *UplinkTXInfo `protobuf:"bytes,2,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// RX meta-data set.
	RxInfo               []*UplinkRXInfo `protobuf:"bytes,3,rep,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UplinkFrameSet) Reset()         { *m = UplinkFrameSet{} }
func (m *UplinkFrameSet) String() string { return proto.CompactTextString(m) }
func (*UplinkFrameSet) ProtoMessage()    {}
func (*UplinkFrameSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_gw_c5d2c5c9c486fb40, []int{8}
}
func (m *UplinkFrameSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UplinkFrameSet.Unmarshal(m, b)
}
func (m *UplinkFrameSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UplinkFrameSet.Marshal(b, m, deterministic)
}
func (dst *UplinkFrameSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UplinkFrameSet.Merge(dst, src)
}
func (m *UplinkFrameSet) XXX_Size() int {
	return xxx_messageInfo_UplinkFrameSet.Size(m)
}
func (m *UplinkFrameSet) XXX_DiscardUnknown() {
	xxx_messageInfo_UplinkFrameSet.DiscardUnknown(m)
}

var xxx_messageInfo_UplinkFrameSet proto.InternalMessageInfo

func (m *UplinkFrameSet) GetPhyPayload() []byte {
	if m != nil {
		return m.PhyPayload
	}
	return nil
}

func (m *UplinkFrameSet) GetTxInfo() *UplinkTXInfo {
	if m != nil {
		return m.TxInfo
	}
	return nil
}

func (m *UplinkFrameSet) GetRxInfo() []*UplinkRXInfo {
	if m != nil {
		return m.RxInfo
	}
	return nil
}

type DownlinkFrame struct {
	// PHYPayload.
	PhyPayload []byte `protobuf:"bytes,1,opt,name=phy_payload,json=phyPayload,proto3" json:"phy_payload,omitempty"`
	// TX meta-data.
	TxInfo *DownlinkTXInfo `protobuf:"bytes,2,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// Token (uint16 value).
	Token                uint32   `protobuf:"varint,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownlinkFrame) Reset()         { *m = DownlinkFrame{} }
func (m *DownlinkFrame) String() string { return proto.CompactTextString(m) }
func (*DownlinkFrame) ProtoMessage()    {}
func (*DownlinkFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_gw_c5d2c5c9c486fb40, []int{9}
}
func (m *DownlinkFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownlinkFrame.Unmarshal(m, b)
}
func (m *DownlinkFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownlinkFrame.Marshal(b, m, deterministic)
}
func (dst *DownlinkFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownlinkFrame.Merge(dst, src)
}
func (m *DownlinkFrame) XXX_Size() int {
	return xxx_messageInfo_DownlinkFrame.Size(m)
}
func (m *DownlinkFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_DownlinkFrame.DiscardUnknown(m)
}

var xxx_messageInfo_DownlinkFrame proto.InternalMessageInfo

func (m *DownlinkFrame) GetPhyPayload() []byte {
	if m != nil {
		return m.PhyPayload
	}
	return nil
}

func (m *DownlinkFrame) GetTxInfo() *DownlinkTXInfo {
	if m != nil {
		return m.TxInfo
	}
	return nil
}

func (m *DownlinkFrame) GetToken() uint32 {
	if m != nil {
		return m.Token
	}
	return 0
}

func init() {
	proto.RegisterType((*UplinkTXInfo)(nil), "gw.UplinkTXInfo")
	proto.RegisterType((*LoRaModulationInfo)(nil), "gw.LoRaModulationInfo")
	proto.RegisterType((*FSKModulationInfo)(nil), "gw.FSKModulationInfo")
	proto.RegisterType((*EncryptedFineTimestamp)(nil), "gw.EncryptedFineTimestamp")
	proto.RegisterType((*PlainFineTimestamp)(nil), "gw.PlainFineTimestamp")
	proto.RegisterType((*UplinkRXInfo)(nil), "gw.UplinkRXInfo")
	proto.RegisterType((*DownlinkTXInfo)(nil), "gw.DownlinkTXInfo")
	proto.RegisterType((*UplinkFrame)(nil), "gw.UplinkFrame")
	proto.RegisterType((*UplinkFrameSet)(nil), "gw.UplinkFrameSet")
	proto.RegisterType((*DownlinkFrame)(nil), "gw.DownlinkFrame")
	proto.RegisterEnum("gw.FineTimestampType", FineTimestampType_name, FineTimestampType_value)
}

func init() { proto.RegisterFile("gw.proto", fileDescriptor_gw_c5d2c5c9c486fb40) }

var fileDescriptor_gw_c5d2c5c9c486fb40 = []byte{
	// 951 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x5b, 0x6f, 0xe3, 0x44,
	0x14, 0xae, 0xd3, 0xa6, 0x49, 0x4e, 0x9a, 0x6e, 0x32, 0x9b, 0xad, 0xbc, 0xe5, 0xb2, 0x21, 0x42,
	0x28, 0x05, 0xe4, 0x48, 0x45, 0x2b, 0x9e, 0xe9, 0x36, 0xdd, 0xcd, 0xb6, 0x84, 0x6a, 0x5a, 0x10,
	0xf0, 0x62, 0x4d, 0xec, 0xb1, 0x33, 0x4a, 0x32, 0x63, 0xc6, 0xce, 0xba, 0xe6, 0x19, 0x01, 0x7f,
	0x87, 0xdf, 0xc7, 0x0b, 0x9a, 0xf1, 0x25, 0xb7, 0x42, 0x17, 0x71, 0x79, 0x72, 0xcf, 0xe7, 0x73,
	0xbe, 0x7e, 0x33, 0xe7, 0x3b, 0xc7, 0x81, 0xaa, 0x1f, 0x5b, 0x81, 0x14, 0x91, 0x40, 0x25, 0x3f,
	0x3e, 0x7e, 0xee, 0xb3, 0x68, 0xb2, 0x18, 0x5b, 0x8e, 0x98, 0xf7, 0xc7, 0x52, 0x38, 0x84, 0xc8,
	0xfe, 0x4c, 0x48, 0x12, 0x52, 0xf9, 0x86, 0xca, 0x3e, 0x09, 0x58, 0xdf, 0x11, 0xf3, 0xb9, 0xe0,
	0xd9, 0x23, 0x2d, 0x3d, 0x7e, 0xe6, 0x0b, 0xe1, 0xcf, 0x68, 0x5f, 0x47, 0xe3, 0x85, 0xd7, 0x8f,
	0xd8, 0x9c, 0x86, 0x11, 0x99, 0x07, 0x59, 0xc2, 0xfb, 0x9b, 0x09, 0xee, 0x42, 0x92, 0x88, 0xe5,
	0x04, 0xdd, 0x5f, 0x4b, 0x70, 0xf0, 0x75, 0x30, 0x63, 0x7c, 0x7a, 0xfb, 0xed, 0x90, 0x7b, 0x02,
	0xbd, 0x0b, 0x35, 0x4f, 0xd2, 0x1f, 0x16, 0x94, 0x3b, 0x89, 0x69, 0x74, 0x8c, 0x5e, 0x03, 0x2f,
	0x01, 0x74, 0x0a, 0x30, 0x17, 0xee, 0x62, 0xa6, 0x29, 0xcc, 0x52, 0xc7, 0xe8, 0x1d, 0x9e, 0x22,
	0x2b, 0x93, 0xf4, 0x65, 0xf1, 0x06, 0xaf, 0x64, 0xa1, 0xd7, 0xd0, 0x56, 0x27, 0xb1, 0x97, 0x90,
	0xcd, 0xb8, 0x27, 0xcc, 0xdd, 0x8e, 0xd1, 0xab, 0x9f, 0x1e, 0x59, 0x7e, 0x6c, 0x5d, 0x09, 0x4c,
	0x96, 0xd5, 0x4a, 0xc7, 0xab, 0x1d, 0x8c, 0x54, 0xd5, 0x3a, 0x8a, 0x5e, 0xc2, 0x63, 0x2f, 0x9c,
	0x6e, 0x51, 0xed, 0x69, 0xaa, 0x27, 0x8a, 0xea, 0xe2, 0xe6, 0x72, 0x8b, 0xa9, 0xe5, 0x85, 0xd3,
	0x75, 0xf0, 0xac, 0x05, 0x8f, 0x36, 0x48, 0xba, 0xbf, 0x19, 0x80, 0xb6, 0x85, 0xa8, 0x0b, 0x19,
	0x13, 0xee, 0xc6, 0xcc, 0x8d, 0x26, 0xf9, 0x85, 0x14, 0x00, 0x3a, 0x81, 0x66, 0x18, 0x48, 0x4a,
	0x5c, 0xc6, 0x7d, 0xdb, 0x23, 0x4e, 0x24, 0xa4, 0xbe, 0x96, 0x06, 0x7e, 0x54, 0xe0, 0x17, 0x1a,
	0x46, 0xef, 0x40, 0xcd, 0x11, 0x2e, 0xb5, 0x25, 0x89, 0xa8, 0x3e, 0x7c, 0x0d, 0x57, 0x15, 0x80,
	0x49, 0x44, 0xd1, 0x73, 0x38, 0x0a, 0xc4, 0x8c, 0x48, 0xf6, 0x63, 0xae, 0xe8, 0x0d, 0x95, 0xa1,
	0xba, 0x64, 0x75, 0xb6, 0x2a, 0x7e, 0xb2, 0xfa, 0x76, 0x98, 0xbf, 0xec, 0x5e, 0x42, 0x6b, 0xeb,
	0xc0, 0x0f, 0x28, 0x36, 0xa1, 0x32, 0x66, 0x91, 0x16, 0x91, 0x0a, 0xcd, 0xc3, 0xae, 0x0d, 0x47,
	0x03, 0xee, 0xc8, 0x24, 0x88, 0xa8, 0x7b, 0xc1, 0x38, 0xbd, 0xcd, 0xbd, 0x84, 0xba, 0xd0, 0x20,
	0x34, 0xb4, 0xa7, 0x34, 0xb1, 0x19, 0x77, 0xe9, 0x5d, 0xc6, 0x5a, 0x27, 0x34, 0xbc, 0xa4, 0xc9,
	0x50, 0x41, 0xe8, 0x03, 0x38, 0xa0, 0x79, 0xb5, 0xcd, 0x43, 0x4d, 0x7e, 0x80, 0xeb, 0x05, 0x36,
	0x0a, 0xbb, 0xe7, 0x80, 0xae, 0x67, 0x84, 0xf1, 0x75, 0x72, 0x0b, 0xf6, 0x94, 0x6b, 0x35, 0x67,
	0xfd, 0xf4, 0xd8, 0x4a, 0x1d, 0x6b, 0xe5, 0x8e, 0xb5, 0x8a, 0x4c, 0xac, 0xf3, 0xba, 0x3f, 0x97,
	0x73, 0xcb, 0xe2, 0xd4, 0xb2, 0xef, 0x01, 0xf8, 0x24, 0xa2, 0x31, 0x49, 0x6c, 0xe6, 0x6a, 0x9a,
	0x03, 0x5c, 0xcb, 0x90, 0xa1, 0x5b, 0xf0, 0x97, 0xde, 0x8e, 0x5f, 0xf9, 0x55, 0x3d, 0xed, 0x90,
	0x71, 0x87, 0xda, 0x7e, 0x10, 0xda, 0x34, 0x10, 0xce, 0x24, 0xf3, 0xeb, 0xd3, 0xad, 0xfa, 0xf3,
	0x6c, 0xa2, 0x70, 0x4b, 0x95, 0xdd, 0xa8, 0xaa, 0x97, 0x41, 0x38, 0x50, 0x35, 0xaa, 0x15, 0xc5,
	0x44, 0xea, 0x4e, 0x36, 0xf0, 0x12, 0x40, 0x08, 0xf6, 0x64, 0x18, 0x32, 0xb3, 0xdc, 0x31, 0x7a,
	0x65, 0xac, 0xff, 0x46, 0x4f, 0xa1, 0xaa, 0xa7, 0x25, 0xe4, 0xd2, 0xdc, 0xef, 0x18, 0x3d, 0x03,
	0x57, 0x54, 0x7c, 0xc3, 0xa5, 0xea, 0x9c, 0x33, 0x21, 0x9c, 0xd3, 0x99, 0x59, 0x49, 0x3b, 0x97,
	0x85, 0xaa, 0x48, 0x7a, 0xb6, 0x33, 0x21, 0x8c, 0x9b, 0xd5, 0xf4, 0x95, 0xf4, 0x5e, 0xa8, 0x10,
	0xb5, 0xa1, 0x3c, 0x16, 0x44, 0xba, 0x66, 0x4d, 0xe3, 0x69, 0xa0, 0xa8, 0x08, 0x8f, 0x28, 0xe7,
	0xc4, 0x84, 0x34, 0x3f, 0x0b, 0xd1, 0xa7, 0xea, 0xff, 0x3b, 0xe9, 0x7c, 0xd7, 0xf5, 0x89, 0x9b,
	0xf9, 0x7c, 0x5f, 0x65, 0x38, 0x2e, 0x32, 0xd0, 0x00, 0x1e, 0x7b, 0x8c, 0x53, 0xbb, 0x38, 0x93,
	0x1d, 0x25, 0x01, 0x35, 0x0f, 0xf4, 0x62, 0x48, 0xe7, 0x71, 0xb5, 0xd7, 0xb7, 0x49, 0x40, 0x71,
	0xcb, 0xdb, 0x84, 0xd0, 0x37, 0x60, 0x2e, 0xbd, 0xb3, 0x4e, 0x68, 0x36, 0xf2, 0xb6, 0xc5, 0xd6,
	0xfd, 0xee, 0x7c, 0xb5, 0x83, 0x8f, 0xe8, 0xfd, 0xbe, 0x7d, 0x0d, 0xed, 0x40, 0x19, 0x6e, 0x93,
	0xf3, 0x70, 0xb9, 0x7a, 0xb6, 0x0d, 0xa9, 0x56, 0x4f, 0xb0, 0x85, 0x9e, 0x35, 0xe1, 0x70, 0x9d,
	0xa5, 0xfb, 0xfb, 0x2e, 0x1c, 0x9e, 0x8b, 0x98, 0xaf, 0x6c, 0xcf, 0x07, 0xac, 0xd8, 0x81, 0x3a,
	0x9b, 0xcf, 0xa9, 0xcb, 0x48, 0x44, 0x67, 0x89, 0x76, 0x64, 0x15, 0xaf, 0x42, 0xff, 0xa3, 0xf9,
	0xd6, 0x16, 0x7d, 0x79, 0x73, 0xd1, 0xb7, 0xa1, 0x1c, 0x88, 0x98, 0xa6, 0x1e, 0x2c, 0xe3, 0x34,
	0xd8, 0x58, 0xff, 0x95, 0x7f, 0xb4, 0xfe, 0xab, 0xff, 0xde, 0xfa, 0xaf, 0xfd, 0xdd, 0xf5, 0xbf,
	0x9c, 0x0a, 0xf8, 0x93, 0xa9, 0xa8, 0xaf, 0x4d, 0xc5, 0x7d, 0x9f, 0x8b, 0x9f, 0x0c, 0xa8, 0xa7,
	0x6b, 0xe8, 0x42, 0x92, 0x39, 0x45, 0xcf, 0xa0, 0x1e, 0x4c, 0x12, 0x3b, 0x20, 0xc9, 0x4c, 0x90,
	0xbc, 0xf7, 0x10, 0x4c, 0x92, 0xeb, 0x14, 0x41, 0x27, 0x50, 0x89, 0xee, 0x52, 0xc1, 0xa5, 0x6c,
	0xb0, 0xfc, 0xd8, 0x5a, 0xfd, 0xf8, 0xe2, 0xfd, 0xe8, 0x4e, 0xcb, 0x3b, 0x81, 0x8a, 0xbc, 0x5b,
	0xfd, 0x4a, 0xae, 0xa4, 0xe2, 0x2c, 0x55, 0xea, 0xd4, 0xee, 0x2f, 0x06, 0x1c, 0xae, 0xc8, 0xb8,
	0xa1, 0xd1, 0x7f, 0xa7, 0x64, 0xf7, 0x2f, 0x95, 0x84, 0xd0, 0xc8, 0xa7, 0xe1, 0x2d, 0x6f, 0xe4,
	0x93, 0x4d, 0x1d, 0x48, 0x91, 0xaf, 0x8f, 0x54, 0xa1, 0xa4, 0x0d, 0xe5, 0x48, 0x4c, 0x29, 0xd7,
	0x37, 0xd2, 0xc0, 0x69, 0xf0, 0xf1, 0xe7, 0xd0, 0xda, 0xda, 0x30, 0xa8, 0x0a, 0x7b, 0xa3, 0xaf,
	0x46, 0x83, 0xe6, 0x0e, 0x6a, 0x40, 0x6d, 0x30, 0x7a, 0x81, 0xbf, 0xbb, 0xbe, 0x1d, 0x9c, 0x37,
	0x0d, 0x54, 0x83, 0xf2, 0xf5, 0xd5, 0x17, 0xc3, 0x51, 0xb3, 0x74, 0xf6, 0xd1, 0xf7, 0x1f, 0x3e,
	0xfc, 0x93, 0xcb, 0x8f, 0xc7, 0xfb, 0x7a, 0xd4, 0x3e, 0xfb, 0x23, 0x00, 0x00, 0xff, 0xff, 0x0a,
	0x50, 0xfb, 0x0f, 0xaf, 0x09, 0x00, 0x00,
}
